
    there three type of array
    1D array
    2D array
    3D array
    higher deminsional array
    Array look like matrix & detarment
    ![alt text](image.png)

In [2]:
import numpy as np

In [11]:
# create array
x = np.array([1,2,3,4,5,6])
print(x)
print(type(x))
%timeit x


[1 2 3 4 5 6]
<class 'numpy.ndarray'>
19.6 ns ± 3.21 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [10]:
list1 = [1,2,3,45]
print(list1)
print(type(list1))

%timeit list1


[1, 2, 3, 45]
<class 'list'>
28.7 ns ± 2.27 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


![alt text](image-1.png)
diffrence array vs list


In [ ]:
l = []
for i in range(1,5):
    int_1 = int(input("Enter Numbe")) #int get
    l.append(int_1)
print(np.array(l))

[ 2  3 22  2]


1D ARRAY


In [ ]:
a = np.array([1,2,3])
print(a)
print(np.ndim(a))
#  ndim thi kbr pade kyo array chhe

[1 2 3]
1


2D ARRAY


In [25]:
b=np.array([[1,2,3],[1,2,5]])
print(b)
print(np.ndim(b))

[[1 2 3]
 [1 2 5]]
2


3D ARRAY


In [29]:
c = np.array([[[1,2,3],[2,5,6],[6,7,8]]])
print(c)
print(np.ndim(c))

[[[1 2 3]
  [2 5 6]
  [6 7 8]]]
3


N DIMENSION ARRAY CREATE`

In [32]:
n = np.array([1,2,3,4] , ndmin=10)
print(n)
print(np.ndim(n))

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10
