CREATE NUMPY ARRAY USING NUMPY FUNCTION


![alt text](image-2.png)

zero array create 

array ni under badha zero j hoi 

In [1]:
import numpy as np

In [ ]:
ar=np.zeros(4)
print("1D   ",ar)
print()

ar2 = np.zeros((3,4))
print("2D   ",ar2)
print()

ar3=np.zeros(((3,4,5)))
print("3D   ",ar3)
print(np.ndim(ar3))

ONES


In [23]:
a = np.ones(5)
print("1D   ",a)
print()

b = np.ones((3,3))
print("2D   " ,b)
print(np.ndim(b))

1D    [1. 1. 1. 1. 1.]

2D    [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
2


EMPTY

In [24]:
e = np.empty(5)
print(e)

[1. 1. 1. 1. 1.]


RANGE ARRAY

In [25]:
arr = np.arange(20)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


Diagnol is 1
[1 0 0
 0 1 0
 0 0 1]

In [26]:
dig = np.eye(3)
print(dig)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Linespace

In [39]:
lin = np.linspace(1,100,num=5)
print(lin)

[  1.    25.75  50.5   75.25 100.  ]
