In [2]:
import numpy as np


CREATE NUMPY ARRAY WITH RANDOM ARRAY

![alt text](image-3.png)

In [5]:
a=np.random.rand(1)
print(a)

[0.82547686]


In [6]:
b=np.random.rand(2,5)
print(b)
print(np.ndim(b))

[[0.54584969 0.52760301 0.6723331  0.83000913 0.18014104]
 [0.00602028 0.1368926  0.60834082 0.2097062  0.98470744]]
2


In [7]:
c = np.random.rand(3,5,2)
print(c)
print(np.ndim(c))

[[[9.02045100e-01 6.76315822e-02]
  [8.15801205e-01 5.09877003e-02]
  [3.54749695e-02 9.05663918e-01]
  [9.87930417e-02 1.55837357e-01]
  [4.01006640e-01 9.84010463e-01]]

 [[9.15567384e-01 3.24636624e-01]
  [6.56384364e-01 9.90475188e-01]
  [3.62417431e-01 7.55472544e-01]
  [3.20355016e-01 1.09487931e-01]
  [8.96077425e-02 6.15466240e-01]]

 [[7.68952562e-01 2.78662856e-01]
  [9.78514121e-01 7.65178588e-01]
  [1.03124677e-01 4.87619331e-01]
  [1.39287271e-01 4.78889380e-01]
  [7.41160799e-02 4.25908188e-04]]]
3


randn()

In [8]:
a = np.random.randn(3)
print(a)
print("\n\n")
b=np.random.randn(2,3)
print(b)
print("\n\n")
c=np.random.randn(2,3,5)
print(c)

[0.03613925 0.63188373 1.07223438]



[[-2.10875444 -2.16519914 -1.31711767]
 [-2.19797292 -0.61103501 -0.33502609]]



[[[-0.48017886  0.02123267  1.29822769  0.99725141  0.25464384]
  [-0.87513331  0.18652236 -0.41983888  1.78186318 -0.32751912]
  [ 0.26796665  0.0412029   0.31797608  0.47752134 -0.79573465]]

 [[-0.43473721  0.92860296  0.69189647  0.61598763 -0.28830002]
  [-0.42377794  0.08568131 -1.09066008  0.7130626  -0.7717553 ]
  [-1.04663152  1.08823568  0.76182632 -0.94092365  0.24290095]]]


ranf()

In [11]:
a=np.random.ranf(3)
print(a)

[0.54187048 0.48920487 0.21490228]


randint()

In [21]:
a=np.random.randint(1000,9999,4)


print(a)


[5336 6283 1050 1407]
