In [ ]:
import numpy as np


CREATE NUMPY ARRAY WITH RANDOM ARRAY

![alt text](image-3.png)

In [ ]:
a=np.random.rand(1)
print(a)

[0.0689743]


In [44]:
b=np.random.rand(2,5)
print(b)
print(np.ndim(b))

[[0.28322135 0.0301812  0.6885416  0.41615181 0.49224539]
 [0.42648457 0.39365009 0.98346384 0.39194277 0.18793741]]
2


In [47]:
c = np.random.rand(3,5,2)
print(c)
print(np.ndim(c))

[[[0.99429805 0.27812802]
  [0.74715061 0.51281919]
  [0.71731803 0.91743783]
  [0.3987521  0.22225671]
  [0.17042162 0.6610166 ]]

 [[0.68014998 0.39049577]
  [0.10948261 0.66843193]
  [0.99587087 0.06210165]
  [0.54462218 0.85921126]
  [0.20555123 0.69173905]]

 [[0.82353758 0.15179228]
  [0.11358878 0.19685808]
  [0.767445   0.21558088]
  [0.74617413 0.26482103]
  [0.40754949 0.98686093]]]
3


randn()

In [51]:
a = np.random.randn(3)
print(a)
print("\n\n")
b=np.random.randn(2,3)
print(b)
print("\n\n")
c=np.random.randn(2,3,5)
print(c)

[ 0.56303526 -0.75127129  0.6308988 ]



[[ 0.81644483  0.0630732  -1.30440312]
 [ 1.44001922  0.40822311  0.2133137 ]]



[[[ 0.75324588 -0.40338726  1.98719598 -1.28185539 -0.25533057]
  [-1.30146379 -0.68836009  0.97070345 -0.38006646  0.15713415]
  [-0.54647339  0.36714915  1.16933549  1.0294364   0.97987428]]

 [[-0.74225409  1.118814   -0.75338862  1.36044692 -0.7684869 ]
  [-0.04656139  1.12386909 -1.43160882  0.34508497 -1.31725629]
  [-0.59563349  0.43892035  0.8835971  -0.65368546 -1.75235809]]]


ranf()

In [56]:
a=np.random.ranf(3)
print(a)

[0.63166587 0.48542587 0.20280254]


randint()

In [ ]:
a=np.random.randint(1000,9999,4)


print(a)


[9734 1800 1886 9785]
