Arthimetic oparation in arrays numpy
![alt text](image-5.png)

In [2]:
import numpy as np

In [3]:
# For 1D array

a = np.array([1,2,3,4])
b = np.array([5,6,7,8])


In [6]:
# signel add
res = a +3
print(res)



[4 5 6 7]


In [8]:
res = a+b
print(res)

[ 6  8 10 12]


In [9]:
res = a-b
print(res)

[-4 -4 -4 -4]


In [14]:
res = a*b
print(res)
print(res.dtype)

[ 5 12 21 32]
int64


In [15]:
res = a/b
print(res)
print(res.dtype)

[0.2        0.33333333 0.42857143 0.5       ]
float64


In [16]:
res = a%b
print(res)
print(res.dtype)

[1 2 3 4]
int64


In [20]:
# using fuction
print("Sum: ",np.add(a,b))
print("Sub: ",np.subtract(a,b))
print("Multi: ",np.multiply(a,b))
print(np.divide(a,b))
print(np.mod(a,b))
print(np.power(a,b))
print(np.reciprocal(a))

Sum:  [ 6  8 10 12]
Sub:  [-4 -4 -4 -4]
Multi:  [ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[1 2 3 4]
[    1    64  2187 65536]
[1 0 0 0]


In [22]:
# 2D ARRAY

a1 = np.array([[1,2,3,4],[3,4,5,4]])
a2=np.array([[2,3,4,5],[3,4,2,2]])

In [27]:

print("Add: -",a1+a2)
print("\n SUb: ",a1-a2)
print("\n Division: ",a1/a2)
print("\n Multi: ",a1*a2)

Add: - [[3 5 7 9]
 [6 8 7 6]]

 SUb:  [[-1 -1 -1 -1]
 [ 0  0  3  2]]

 Division:  [[0.5        0.66666667 0.75       0.8       ]
 [1.         1.         2.5        2.        ]]

 Multi:  [[ 2  6 12 20]
 [ 9 16 10  8]]


In [28]:
print(np.add(a1,a2))

[[3 5 7 9]
 [6 8 7 6]]
