Arithmetic Fuctions

![alt text](image-6.png)

In [1]:
import numpy as np

In [5]:
a = np.array([0,23,3,2,2,1,3,4,3])

In [ ]:
print(np.min(a),np.argmin(a)) # argmin show position number / index number

0 0


In [12]:
print(np.max(a), np.argmax(a))

23 1


In [19]:
b= np.array([[2,3,4],[14,6,1]])

In [24]:
print(np.min(b,axis=1))  #asix = 0 is colum ma kam kare , asix =1 is row ma kam kare 
print(np.min(b,axis=0))  #asix = 0 is colum ma kam kare , asix =1 is row ma kam kare 


[2 1]
[2 3 1]


In [28]:
c = np.array([1,2,3])

print(np.sin(c))
print(np.cos(c))

[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]


In [29]:
# cumsum

print(np.cumsum(c))

[1 3 6]
