Shape & ReShape

Shape

In [3]:
import numpy as np

In [4]:
a = np.array([[12,32,32],[2,3,3]])

In [7]:
print(a)
print()
print("Shape", a.shape)

[[12 32 32]
 [ 2  3  3]]

Shape (2, 3)


In [12]:
b = np.array([1,2,3,4],ndmin=10)
print(b,np.ndim(b))

[[[[[[[[[[1 2 3 4]]]]]]]]]] 10


In [13]:
print("SHape",b.shape)

SHape (1, 1, 1, 1, 1, 1, 1, 1, 1, 4)


In [14]:
# Reshape 

In [46]:
c = np.array([1,2,3,4,5,6,1,2])

In [48]:
x = c.reshape(4,2)
print(x)
print(np.ndim(x))

[[1 2]
 [3 4]
 [5 6]
 [1 2]]
2


In [65]:
d = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
x3 = d.reshape(3,2,2)
print(x3)
print(x3.ndim)

#  transfer to 

one = x3.reshape(6,2)
print(one)
print(one.ndim)


# transefer to 1
print()
two = one.reshape(-1)
print(two)
print(two.ndim)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
3
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
2

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1


![alt text](image-7.png)
![alt text](image-8.png)