# BroadCasting

In [1]:
import numpy as np

In [2]:
var1 = np.array([1,2,3])
var2 = np.array([1,2,3])
print (var1 + var2)

[2 4 6]


In [6]:
a = np.array([1,2,3])
b= np.array([[1],[2],[3]])

print("SHapes:")
print(a.shape)
print()
print(b.shape)

print("\n",a)
print("\n",b)

print()

print(a+b)

SHapes:
(3,)

(3, 1)

 [1 2 3]

 [[1]
 [2]
 [3]]

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [10]:
x=np.array([[1],[2]])
z=np.array([[1,2,3],[1,2,3]])

print("Array\n")
print(x,"\n")
print(z,"\n")
print(x.shape)
print(z.shape)

print("\n",x+z)

Array

[[1]
 [2]] 

[[1 2 3]
 [1 2 3]] 

(2, 1)
(2, 3)

 [[2 3 4]
 [3 4 5]]
